USE [master]
GO
CREATE DATABASE [Atividade]
 CONTAINMENT = NONE
GO
ALTER DATABASE [Atividade] SET COMPATIBILITY_LEVEL = 130
GO
IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [Atividade].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO
ALTER DATABASE [Atividade] SET ANSI_NULL_DEFAULT OFF 
GO
ALTER DATABASE [Atividade] SET ANSI_NULLS OFF 
GO
ALTER DATABASE [Atividade] SET ANSI_PADDING OFF 
GO
ALTER DATABASE [Atividade] SET ANSI_WARNINGS OFF 
GO
ALTER DATABASE [Atividade] SET ARITHABORT OFF 
GO
ALTER DATABASE [Atividade] SET AUTO_CLOSE ON 
GO
ALTER DATABASE [Atividade] SET AUTO_SHRINK OFF 
GO
ALTER DATABASE [Atividade] SET AUTO_UPDATE_STATISTICS ON 
GO
ALTER DATABASE [Atividade] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO
ALTER DATABASE [Atividade] SET CURSOR_DEFAULT  GLOBAL 
GO
ALTER DATABASE [Atividade] SET CONCAT_NULL_YIELDS_NULL OFF 
GO
ALTER DATABASE [Atividade] SET NUMERIC_ROUNDABORT OFF 
GO
ALTER DATABASE [Atividade] SET QUOTED_IDENTIFIER OFF 
GO
ALTER DATABASE [Atividade] SET RECURSIVE_TRIGGERS OFF 
GO
ALTER DATABASE [Atividade] SET  ENABLE_BROKER 
GO
ALTER DATABASE [Atividade] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO
ALTER DATABASE [Atividade] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO
ALTER DATABASE [Atividade] SET TRUSTWORTHY OFF 
GO
ALTER DATABASE [Atividade] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO
ALTER DATABASE [Atividade] SET PARAMETERIZATION SIMPLE 
GO
ALTER DATABASE [Atividade] SET READ_COMMITTED_SNAPSHOT OFF 
GO
ALTER DATABASE [Atividade] SET HONOR_BROKER_PRIORITY OFF 
GO
ALTER DATABASE [Atividade] SET RECOVERY SIMPLE 
GO
ALTER DATABASE [Atividade] SET  MULTI_USER 
GO
ALTER DATABASE [Atividade] SET PAGE_VERIFY CHECKSUM  
GO
ALTER DATABASE [Atividade] SET DB_CHAINING OFF 
GO
ALTER DATABASE [Atividade] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO
ALTER DATABASE [Atividade] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO
ALTER DATABASE [Atividade] SET DELAYED_DURABILITY = DISABLED 
GO
ALTER DATABASE [Atividade] SET QUERY_STORE = OFF
GO
USE [Atividade]
GO
ALTER DATABASE SCOPED CONFIGURATION SET LEGACY_CARDINALITY_ESTIMATION = OFF;
GO
ALTER DATABASE SCOPED CONFIGURATION SET MAXDOP = 0;
GO
ALTER DATABASE SCOPED CONFIGURATION SET PARAMETER_SNIFFING = ON;
GO
ALTER DATABASE SCOPED CONFIGURATION SET QUERY_OPTIMIZER_HOTFIXES = OFF;
GO
USE [Atividade]
GO
/****** Object:  Table [dbo].[Aluno]    Script Date: 02/02/2021 23:04:16 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Aluno](
	[Id] [int] NOT NULL,
	[Curso] [varchar](250) NULL,
	[DataMatricula] [datetime] NULL
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[Funcionario]    Script Date: 02/02/2021 23:04:16 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Funcionario](
	[Id] [int] NOT NULL,
	[DataAdmissao] [datetime] NULL,
	[Cargo] [varchar](250) NULL
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[Pessoa]    Script Date: 02/02/2021 23:04:16 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Pessoa](
	[Id] [int] IDENTITY(1,1) NOT NULL,
	[Nome] [varchar](250) NULL,
	[Email] [varchar](250) NULL,
 CONSTRAINT [PK_Pessoa] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Index [IX_Funcionario]    Script Date: 02/02/2021 23:04:16 ******/
CREATE NONCLUSTERED INDEX [IX_Funcionario] ON [dbo].[Funcionario]
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
GO
ALTER TABLE [dbo].[Aluno]  WITH CHECK ADD  CONSTRAINT [FK_Aluno_Pessoa] FOREIGN KEY([Id])
REFERENCES [dbo].[Pessoa] ([Id])
GO
ALTER TABLE [dbo].[Aluno] CHECK CONSTRAINT [FK_Aluno_Pessoa]
GO
ALTER TABLE [dbo].[Funcionario]  WITH CHECK ADD  CONSTRAINT [FK_Funcionario_Pessoa] FOREIGN KEY([Id])
REFERENCES [dbo].[Pessoa] ([Id])
GO
ALTER TABLE [dbo].[Funcionario] CHECK CONSTRAINT [FK_Funcionario_Pessoa]
GO
USE [master]
GO
ALTER DATABASE [Atividade] SET  READ_WRITE 
GO
